make the font list sorted
Wox-launcher/Wox pull request #1263
Opened 2017-03-01 02:57 UTC by danisein

fix #790

2017-03-01 23:51 UTC, bao-qian requested changes

2017-03-01 23:51 UTC, bao-qian commented on Wox/SettingWindow.xaml
> -                    <TextBlock Text="{DynamicResource lastQueryMode}" />
please remove the indent here

2017-03-02 02:56 UTC, danisein commented on Wox/SettingWindow.xaml
> -                    <TextBlock Text="{DynamicResource lastQueryMode}" />
done. sorry for my incaution

2017-03-02 11:07 UTC, bao-qian approved these changes

2017-03-02 11:07 UTC, merged

2017-03-02 11:15 UTC, happlebao commented
Thanks for your contribution@