Added function to open recycle bin
Wox-launcher/Wox pull request #1382
Opened 2017-04-19 16:24 UTC by SweBeat

2017-05-20 13:13 UTC, lances101 commented
@SweBeat I am sorry, but both me and @happlebao are busy with other projects and issues. Once development resumes we will review your PR. Thank you for your contribution.

2017-06-22 17:27 UTC, tinymins requested changes
Add Chinese Translation

2017-06-22 17:27 UTC, tinymins commented on Plugins/Wox.Plugin.Sys/Languages/zh-cn.xaml
>      <system:String x:Key="wox_plugin_sys_emptyrecyclebin">Empty recycle bin</system:String>
清空回收站

2017-06-22 17:27 UTC, tinymins commented on Plugins/Wox.Plugin.Sys/Languages/zh-cn.xaml
> +    <system:String x:Key="wox_plugin_sys_openrecyclebin">Missing translation for: Open recycle bin</system:String>
打开回收站

2019-02-23 06:30 UTC, jhdxr commented
closed since author has abonded this PR (source repo not exists)

2019-02-23 06:30 UTC, closed without merging