Add everything plugin context menu and add settings in Url plugin
Wox-launcher/Wox pull request #2299
Opened 2018-12-20 02:49 UTC by magicdmer

1. Add useful context menu items in everything, copy code follow and complete translation
[https://github.com/Wox-launcher/Wox/pull/2179](https://github.com/Wox-launcher/Wox/pull/2179)

2. Add settings in Url plugin, can set browser path , and it can be a example for plugin setting

2018-12-20 12:39 UTC, jhdxr requested changes

2018-12-20 12:39 UTC, jhdxr commented on Plugins/Wox.Plugin.Url/SettingsControl.xaml.cs
> +            fileBrowserDialog.Filter = "程序文件(*.exe)|*.exe|所有文件|*.*";
请把多语言相关的内容放入语言包，或者默认使用英文。（推荐前者）

2018-12-20 12:41 UTC, jhdxr commented
I'm wondering why you need settings for browser. Wox should open the default browser, which can be changed in the control panel.

2018-12-20 13:03 UTC, magicdmer commented
> I'm wondering why you need settings for browser. Wox should open the default browser, which can be changed in the control panel.
因为我遇到这种奇葩的情况了，我装了360极速浏览器，发现这货竟然没关联url，也没法设置，所以只能选了..

2018-12-20 13:36 UTC, magicdmer commented
改好了，需要再提交一次吗

2018-12-21 07:31 UTC, jhdxr commented
> 
> 
> > I'm wondering why you need settings for browser. Wox should open the default browser, which can be changed in the control panel.
> 
> 因为我遇到这种奇葩的情况了，我装了360极速浏览器，发现这货竟然没关联url，也没法设置，所以只能选了.. 另外我发现wox没有基础的创建设置界面的例子，正好练一下手

这个不需要浏览器提供设置项，windows本身就有：https://support.microsoft.com/zh-cn/help/4028606/windows-10-change-your-default-browser



> 
> 
> 改好了，需要再提交一次吗

不用。在上面的疑问全部确认后我会merge

2018-12-25 06:53 UTC, magicdmer commented
>这个不需要浏览器提供设置项，windows本身就有：https://support.microsoft.com/zh-cn/help/4028606/windows-10-change-your-default-browser
windows自带的我当然是试过的，不然我也不会去改插件。。，360极速还真不行

2018-12-25 07:11 UTC, merged